brew:
  github:
    owner: goreleaser
    name: homebrew-tap
  folder: Formula
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
dockers:
  - image: goreleaser/example
    latest: true
