builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
dockers:
  - image: goreleaser/example
    latest: true
brew:
  github:
    owner: goreleaser
    name: homebrew-tap
  folder: Formula
  homepage:  http://goreleaser.github.io
  description: GoReleaser example repository
fpm:
  homepage:  http://goreleaser.github.io
  description: GoReleaser example repository
  maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
  license: MIT
  vendor: GoReleaser
  formats:
    - deb
    - rpm
  dependencies:
    - git
snapcraft:
  summary: GoReleaser example repository
  description: GoReleaser example repository
  grade: stable
  confinement: classic
