dist: trusty
sudo: required
language: go
go: 1.9
services:
  - docker
install:
  - go get ./...
script: go test ./...
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - gem install fpm
  - sudo apt-get update
  - sudo apt-get install --yes snapd rpm
  - export PATH=/snap/bin:$PATH
  - sudo snap install snapcraft --candidate --classic
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
